### PR TITLE
Update install.yml

### PR DESCRIPTION
**Pull request by wavyx**
Fix the fact declaration for "sdkman_dir" environment variable

### CODE REVIEW

**Comment by wavyx** [comment]
The reference to .stdout doesn't work on Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64) with Ansible 2.7.6

> TASK [comcast.sdkman : Set SDKMAN_DIR environment variable] ******************************************************************************************************************************************************
> fatal: [es01.data.be]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/root/infrastructure/ansible/roles/comcast.sdkman/tasks/install.yml': line 20, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set SDKMAN_DIR environment variable\n  ^ here\n"}

**Comment by elliotweiser** [comment]
I don't think that's true. This is tested with Bionic and Ansible 2.7.4. I can upgrade this to Ansible 2.7.6, but I don't anticipate much of a difference.

https://travis-ci.org/Comcast/ansible-sdkman/jobs/487460587

Is it possible that you're setting this variable upstream? I think it's more likely that this a configuration issue.

**Comment by wavyx** [comment]
Indeed in my group_vars I have
sdkman_dir: /usr/local/sdkman

but then it should use the defined value and not fail on
```
- name: Set SDKMAN_DIR environment variable
  set_fact:
    sdkman_dir: '{{ sdkman_dir | default(sdkman_user_home_dir) + "/.sdkman" }}'
```

**Comment by elliotweiser** [comment]
Ok. That sounds like a different issue. Please open an issue with as much detail as you can provide and I'll look into it shortly.

I think SDKMAN removed some older Java packages, so we'll need to update the CI tests anyway.

**Comment by elliotweiser** [comment]
@wavyx Thanks for the contribution. I patched the behavior you identified, so I think this PR has been superseded. Let me know if you encounter any more issues with user-defined `SDKMAN_DIR`.
